language: node_js
node_js:
  - '10.15.0'
dist: trusty
services:
  - mongodb
  - redis-server
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
script:
  # Comment out tests until we have an MVP.
  - exit 0
  - nohup npm run start &
  - sleep 3
  - npm run test
