version: '3'
services:
  mongo:
    image: 'mongo:latest'
  redis:
    image: 'redis:latest'
  router:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: './router'
    ports:
      - '5000:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - .client:/app
  # worker:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: './worker'
  #   volumes:
  #     - /app/node_modules
  #     - ./worker:/app
  # DONT FORGET, add worker into Dockerrun.aws.json
